// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteInvocation.protoc

package com.playtika.remoting.protobuf;

public final class RemoteInvocationProtoc {
  private RemoteInvocationProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RemoteInvocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string method = 1;
    /**
     * <code>required string method = 1;</code>
     */
    boolean hasMethod();
    /**
     * <code>required string method = 1;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>required string method = 1;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    // repeated .protobuf.MessageWrapper argument = 2;
    /**
     * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
     */
    java.util.List<com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper> 
        getArgumentList();
    /**
     * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
     */
    com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper getArgument(int index);
    /**
     * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
     */
    int getArgumentCount();
    /**
     * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
     */
    java.util.List<? extends com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapperOrBuilder> 
        getArgumentOrBuilderList();
    /**
     * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
     */
    com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapperOrBuilder getArgumentOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.RemoteInvocation}
   */
  public static final class RemoteInvocation extends
      com.google.protobuf.GeneratedMessage
      implements RemoteInvocationOrBuilder {
    // Use RemoteInvocation.newBuilder() to construct.
    private RemoteInvocation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RemoteInvocation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RemoteInvocation defaultInstance;
    public static RemoteInvocation getDefaultInstance() {
      return defaultInstance;
    }

    public RemoteInvocation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RemoteInvocation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              method_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                argument_ = new java.util.ArrayList<com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper>();
                mutable_bitField0_ |= 0x00000002;
              }
              argument_.add(input.readMessage(com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          argument_ = java.util.Collections.unmodifiableList(argument_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.playtika.remoting.protobuf.RemoteInvocationProtoc.internal_static_protobuf_RemoteInvocation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.playtika.remoting.protobuf.RemoteInvocationProtoc.internal_static_protobuf_RemoteInvocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation.class, com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation.Builder.class);
    }

    public static com.google.protobuf.Parser<RemoteInvocation> PARSER =
        new com.google.protobuf.AbstractParser<RemoteInvocation>() {
      public RemoteInvocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RemoteInvocation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RemoteInvocation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string method = 1;
    public static final int METHOD_FIELD_NUMBER = 1;
    private java.lang.Object method_;
    /**
     * <code>required string method = 1;</code>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string method = 1;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          method_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string method = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .protobuf.MessageWrapper argument = 2;
    public static final int ARGUMENT_FIELD_NUMBER = 2;
    private java.util.List<com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper> argument_;
    /**
     * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
     */
    public java.util.List<com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper> getArgumentList() {
      return argument_;
    }
    /**
     * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
     */
    public java.util.List<? extends com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapperOrBuilder> 
        getArgumentOrBuilderList() {
      return argument_;
    }
    /**
     * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
     */
    public int getArgumentCount() {
      return argument_.size();
    }
    /**
     * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
     */
    public com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper getArgument(int index) {
      return argument_.get(index);
    }
    /**
     * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
     */
    public com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapperOrBuilder getArgumentOrBuilder(
        int index) {
      return argument_.get(index);
    }

    private void initFields() {
      method_ = "";
      argument_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMethodBytes());
      }
      for (int i = 0; i < argument_.size(); i++) {
        output.writeMessage(2, argument_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMethodBytes());
      }
      for (int i = 0; i < argument_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, argument_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.RemoteInvocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.playtika.remoting.protobuf.RemoteInvocationProtoc.internal_static_protobuf_RemoteInvocation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.playtika.remoting.protobuf.RemoteInvocationProtoc.internal_static_protobuf_RemoteInvocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation.class, com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation.Builder.class);
      }

      // Construct using com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getArgumentFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        method_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (argumentBuilder_ == null) {
          argument_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          argumentBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.playtika.remoting.protobuf.RemoteInvocationProtoc.internal_static_protobuf_RemoteInvocation_descriptor;
      }

      public com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation getDefaultInstanceForType() {
        return com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation.getDefaultInstance();
      }

      public com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation build() {
        com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation buildPartial() {
        com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation result = new com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.method_ = method_;
        if (argumentBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            argument_ = java.util.Collections.unmodifiableList(argument_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.argument_ = argument_;
        } else {
          result.argument_ = argumentBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation) {
          return mergeFrom((com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation other) {
        if (other == com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation.getDefaultInstance()) return this;
        if (other.hasMethod()) {
          bitField0_ |= 0x00000001;
          method_ = other.method_;
          onChanged();
        }
        if (argumentBuilder_ == null) {
          if (!other.argument_.isEmpty()) {
            if (argument_.isEmpty()) {
              argument_ = other.argument_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureArgumentIsMutable();
              argument_.addAll(other.argument_);
            }
            onChanged();
          }
        } else {
          if (!other.argument_.isEmpty()) {
            if (argumentBuilder_.isEmpty()) {
              argumentBuilder_.dispose();
              argumentBuilder_ = null;
              argument_ = other.argument_;
              bitField0_ = (bitField0_ & ~0x00000002);
              argumentBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getArgumentFieldBuilder() : null;
            } else {
              argumentBuilder_.addAllMessages(other.argument_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMethod()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.playtika.remoting.protobuf.RemoteInvocationProtoc.RemoteInvocation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string method = 1;
      private java.lang.Object method_ = "";
      /**
       * <code>required string method = 1;</code>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string method = 1;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string method = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string method = 1;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string method = 1;</code>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000001);
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>required string method = 1;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        method_ = value;
        onChanged();
        return this;
      }

      // repeated .protobuf.MessageWrapper argument = 2;
      private java.util.List<com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper> argument_ =
        java.util.Collections.emptyList();
      private void ensureArgumentIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          argument_ = new java.util.ArrayList<com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper>(argument_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper, com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.Builder, com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapperOrBuilder> argumentBuilder_;

      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public java.util.List<com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper> getArgumentList() {
        if (argumentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(argument_);
        } else {
          return argumentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public int getArgumentCount() {
        if (argumentBuilder_ == null) {
          return argument_.size();
        } else {
          return argumentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper getArgument(int index) {
        if (argumentBuilder_ == null) {
          return argument_.get(index);
        } else {
          return argumentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public Builder setArgument(
          int index, com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper value) {
        if (argumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgumentIsMutable();
          argument_.set(index, value);
          onChanged();
        } else {
          argumentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public Builder setArgument(
          int index, com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.Builder builderForValue) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          argument_.set(index, builderForValue.build());
          onChanged();
        } else {
          argumentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public Builder addArgument(com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper value) {
        if (argumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgumentIsMutable();
          argument_.add(value);
          onChanged();
        } else {
          argumentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public Builder addArgument(
          int index, com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper value) {
        if (argumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgumentIsMutable();
          argument_.add(index, value);
          onChanged();
        } else {
          argumentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public Builder addArgument(
          com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.Builder builderForValue) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          argument_.add(builderForValue.build());
          onChanged();
        } else {
          argumentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public Builder addArgument(
          int index, com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.Builder builderForValue) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          argument_.add(index, builderForValue.build());
          onChanged();
        } else {
          argumentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public Builder addAllArgument(
          java.lang.Iterable<? extends com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper> values) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          super.addAll(values, argument_);
          onChanged();
        } else {
          argumentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public Builder clearArgument() {
        if (argumentBuilder_ == null) {
          argument_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          argumentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public Builder removeArgument(int index) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          argument_.remove(index);
          onChanged();
        } else {
          argumentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.Builder getArgumentBuilder(
          int index) {
        return getArgumentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapperOrBuilder getArgumentOrBuilder(
          int index) {
        if (argumentBuilder_ == null) {
          return argument_.get(index);  } else {
          return argumentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public java.util.List<? extends com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapperOrBuilder> 
           getArgumentOrBuilderList() {
        if (argumentBuilder_ != null) {
          return argumentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(argument_);
        }
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.Builder addArgumentBuilder() {
        return getArgumentFieldBuilder().addBuilder(
            com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.Builder addArgumentBuilder(
          int index) {
        return getArgumentFieldBuilder().addBuilder(
            index, com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.MessageWrapper argument = 2;</code>
       */
      public java.util.List<com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.Builder> 
           getArgumentBuilderList() {
        return getArgumentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper, com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.Builder, com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapperOrBuilder> 
          getArgumentFieldBuilder() {
        if (argumentBuilder_ == null) {
          argumentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper, com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.Builder, com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapperOrBuilder>(
                  argument_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          argument_ = null;
        }
        return argumentBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.RemoteInvocation)
    }

    static {
      defaultInstance = new RemoteInvocation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.RemoteInvocation)
  }

  public interface MessageWrapperOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string class_name = 1;
    /**
     * <code>optional string class_name = 1;</code>
     */
    boolean hasClassName();
    /**
     * <code>optional string class_name = 1;</code>
     */
    java.lang.String getClassName();
    /**
     * <code>optional string class_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    // optional bytes data = 2;
    /**
     * <code>optional bytes data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code protobuf.MessageWrapper}
   */
  public static final class MessageWrapper extends
      com.google.protobuf.GeneratedMessage
      implements MessageWrapperOrBuilder {
    // Use MessageWrapper.newBuilder() to construct.
    private MessageWrapper(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageWrapper(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageWrapper defaultInstance;
    public static MessageWrapper getDefaultInstance() {
      return defaultInstance;
    }

    public MessageWrapper getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              className_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.playtika.remoting.protobuf.RemoteInvocationProtoc.internal_static_protobuf_MessageWrapper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.playtika.remoting.protobuf.RemoteInvocationProtoc.internal_static_protobuf_MessageWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.class, com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageWrapper> PARSER =
        new com.google.protobuf.AbstractParser<MessageWrapper>() {
      public MessageWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageWrapper(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageWrapper> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string class_name = 1;
    public static final int CLASS_NAME_FIELD_NUMBER = 1;
    private java.lang.Object className_;
    /**
     * <code>optional string class_name = 1;</code>
     */
    public boolean hasClassName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string class_name = 1;</code>
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          className_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string class_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      className_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getClassNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getClassNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.MessageWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.playtika.remoting.protobuf.RemoteInvocationProtoc.internal_static_protobuf_MessageWrapper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.playtika.remoting.protobuf.RemoteInvocationProtoc.internal_static_protobuf_MessageWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.class, com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.Builder.class);
      }

      // Construct using com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        className_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.playtika.remoting.protobuf.RemoteInvocationProtoc.internal_static_protobuf_MessageWrapper_descriptor;
      }

      public com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper getDefaultInstanceForType() {
        return com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.getDefaultInstance();
      }

      public com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper build() {
        com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper buildPartial() {
        com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper result = new com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.className_ = className_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper) {
          return mergeFrom((com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper other) {
        if (other == com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper.getDefaultInstance()) return this;
        if (other.hasClassName()) {
          bitField0_ |= 0x00000001;
          className_ = other.className_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.playtika.remoting.protobuf.RemoteInvocationProtoc.MessageWrapper) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string class_name = 1;
      private java.lang.Object className_ = "";
      /**
       * <code>optional string class_name = 1;</code>
       */
      public boolean hasClassName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string class_name = 1;</code>
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          className_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string class_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string class_name = 1;</code>
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string class_name = 1;</code>
       */
      public Builder clearClassName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string class_name = 1;</code>
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        className_ = value;
        onChanged();
        return this;
      }

      // optional bytes data = 2;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.MessageWrapper)
    }

    static {
      defaultInstance = new MessageWrapper(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.MessageWrapper)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_RemoteInvocation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_RemoteInvocation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_MessageWrapper_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_MessageWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027RemoteInvocation.protoc\022\010protobuf\"N\n\020R" +
      "emoteInvocation\022\016\n\006method\030\001 \002(\t\022*\n\010argum" +
      "ent\030\002 \003(\0132\030.protobuf.MessageWrapper\"2\n\016M" +
      "essageWrapper\022\022\n\nclass_name\030\001 \001(\t\022\014\n\004dat" +
      "a\030\002 \001(\014B#\n\036com.playtika.remoting.protobu" +
      "f\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_RemoteInvocation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_RemoteInvocation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_RemoteInvocation_descriptor,
              new java.lang.String[] { "Method", "Argument", });
          internal_static_protobuf_MessageWrapper_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_MessageWrapper_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_MessageWrapper_descriptor,
              new java.lang.String[] { "ClassName", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
